plugins:
  - rubocop-rspec

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.2
  Exclude:
    - 'vendor/**/*'
    - 'tmp/**/*'
    - 'coverage/**/*'
    - 'spec/split_test_rb/dummy_*.rb'

Style/StringLiterals:
  EnforcedStyle: single_quotes

Style/Documentation:
  Enabled: false

Layout/LineLength:
  Max: 120

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - '*.gemspec'

Metrics/MethodLength:
  Max: 35

Metrics/AbcSize:
  Max: 45

Metrics/ClassLength:
  Max: 130

RSpec/MultipleExpectations:
  Max: 10

RSpec/ExampleLength:
  Max: 30

RSpec/IdenticalEqualityAssertion:
  Enabled: false

RSpec/ExpectActual:
  Enabled: false

Gemspec/DevelopmentDependencies:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false
